// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClTu7r8slI0W4aZY9ZASL6RwDJrRsBHKk',
    appId: '1:989869560357:web:6f28328f99e814f8c1a5cc',
    messagingSenderId: '989869560357',
    projectId: 'hotel-booking-dc94b',
    authDomain: 'hotel-booking-dc94b.firebaseapp.com',
    storageBucket: 'hotel-booking-dc94b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKO_DJ4cFHjL5TQ2McYZ8U3zF4pw6NACc',
    appId: '1:989869560357:android:52a14f6d8f7efef3c1a5cc',
    messagingSenderId: '989869560357',
    projectId: 'hotel-booking-dc94b',
    storageBucket: 'hotel-booking-dc94b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcpF2rcrlWtWDEulAkfWzK56x8GnWmK9o',
    appId: '1:989869560357:ios:16c84be07df5e73dc1a5cc',
    messagingSenderId: '989869560357',
    projectId: 'hotel-booking-dc94b',
    storageBucket: 'hotel-booking-dc94b.appspot.com',
    iosBundleId: 'com.example.hotelbooking',
  );
}
